
CREATE TABLE REQUEST(
  REQUEST_ID VARCHAR2(256) NOT NULL,
  REQUEST CLOB,
  CREATED_DATE TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT REQUEST_PK PRIMARY KEY (REQUEST_ID)
);



CREATE TABLE DATA(
  DATA_ID VARCHAR2(256) NOT NULL,
  DATA CLOB,
  CREATED_DATE TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT DATA_PK PRIMARY KEY (DATA_ID)
);
