
CREATE TABLE FORESPOERSEL(
  FORESPOERSEL_ID VARCHAR2(256) NOT NULL,
  FORESPOERSEL CLOB,
  OPPRETTET_DATO TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,

	CONSTRAINT FORESPOERSEL_PK PRIMARY KEY (FORESPOERSEL_ID)
);
